name: Build AnarchyEconomy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Ustaw Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Ustaw Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.1.0'

      - name: Zbuduj plugin
        run: gradle build

      - name: Zapisz gotowy JAR
        uses: actions/upload-artifact@v4
        with:
          name: AnarchyEconomy-JAR
          path: build/libs/*.jar
